### ISSUE TITLE
[Discussion] Autorino vs Istio

### ISSUE THREAD

**Issue by wtrocki** [Kuadrant/authorino#149]
Hi

This is more question than issue. I was curious what would be the reason for someone to use authorino that already have istio configued?

Having information in Readme.md about how authorino compares to istio/keycloak operator will be great.
Would mixing Istio and Authorino would be good idea?

Is project production ready?

**Comment by guicassolato** [comment]
@wtrocki, the comparisons to [Istio Authorization](https://istio.io/latest/docs/concepts/security/#authorization) and to [Keycloak Authorization Services](https://www.keycloak.org/docs/latest/authorization_services/index.html) have been recurring since we introduced Authorino. Thanks for asking about it here. It gives us the chance to provide not only you, but the community, with an answer that covers at least some important things on the topic.

The way I see it, there are similarities, but also complementarity between Authorino and Istio auth features.

Keycloak is a different story, which Authorino has a lot more synergies with than I’m able to cover here. Let’s just say for now that today Authorino partners by adding integration via reverse proxy for the OAuth/OIDC authentication use-case, and (hopefully) in the future can perhaps help boost authorization services in an entire new way.

Istio provides a handy way to enable features that are, in many cases, features of Envoy, such as authorization based on JWTs, authorization based on attributes of the request, and activation of external authorization services, without having to deal with complex Envoy config files. (See [Kuadrant](https://github.com/kuadrant/kuadrant-controller) for an alternative, though yet leveraging features of Istio as well.)

Authorino is an Envoy-compatible external authorization service. One can use Authorino with or without Istio.

In particular, [Istio Authorization Policies](https://istio.io/latest/docs/reference/config/security/authorization-policy/) can be seen, in terms of functionality and expressiveness, as a subset of one type of authorization policies supported by Authorino, the [JSON pattern-matching authorization policies](https://github.com/Kuadrant/authorino/blob/693d60d87340eca811094ea965b7ceb0892af289/install/crd/authorino.3scale.net_authconfigs.yaml#L80). While Envoy, nonetheless, is heavily focused on specific use cases of API Management, offering a relatively limited list of [supported attribute conditions](https://istio.io/latest/docs/reference/config/security/conditions/), I believe Authorino is more generic, allowing to express authorization rules for a wider spectrum of use cases – ACLs, RBAC, ABAC, etc, pretty much counting on any attribute of the Envoy payload, identity object and external metadata available.

Apart from that, Authorino also provides built-in OPA authorization, several other methods of authentication and identity verification (Kubernetes token validation, API keys, OAuth token introspection, OIDC-discoverable JWT verification; soon, MTLS and HMAC authn as well), and features like fetching of external metadata (HTTP services, OIDC userinfo, UMA resource data), token normalization, wristband tokens and dynamic responses. These all can be used independently or combined, in a simple and straightforward cloud-native fashion.

With that, Authorino brings a quite interesting package IMO. It covers today auth methods and protocols that Red Hat customers have been requesting and pointing to for their future needs for API security (e.g. relying more on K8s, OIDC, RBAC, Edge auth arch, OPA, external policy registries, etc), yet offering a path for supporting the legacy.

By decoupling from Envoy, very soon Authorino will open up for even more use cases beyond API protection.

<br/>

> what would be the reason for someone to use authorino that already have istio configued?

If you think on each feature individually, there are always other ways to achieve what you want of course, but I think that Authorino’s biggest strengths are simplicity, flexibility and interoperability. One may want to value in a policy enforcer:
1. multiple supported methods and protocols for rather hybrid authentication, encompassing future and legacy auth needs;
2. more expressiveness and more functionalities for the authorization rules;
3. authentication and authorization in one single manifest;
4. capacity to fetch auth metadata on-the-fly;
5. built-in OPA;
6. easy token normalization and/or edge authentication;
7. going beyond API security;

I am sure I’m missing things here, but I hope we have enough to kick-off that entry in Authorino’s README that you have suggested. (Good idea, BTW. Thanks!)

<br/>

> Is project production ready?

No, it isn’t. 

So far, we have mainly focused on feature coverage. But there are a few things we need to do before recommending Authorino for production. E.g.:
- add more caching
- avoid some sensitive data from leaking to the logs (enabled in this early stage of the project for debugging purposes only, but easy to turn off)
- establish some performance benchmarks
