### ISSUE TITLE
Readiness Probe

### ISSUE THREAD

**Issue by OperationalDev** [Kuadrant/authorino#355]
### Challenge
When restarting authorino deployments (with 3 replicas and a pdb), for a few brief seconds, requests are denied with a 403. 

### Solution
Have a healtz endpoint that can be used as a readiness probe that is true when all of the auth configs have been loaded.

**Comment by guicassolato** [comment]
@OperationalDev, are you using the [`Status`](https://github.com/Kuadrant/authorino/blob/a8082ec35cfd112513fd0fb326c261fe153fb423/api/v1beta1/auth_config_types.go#L692) block of the AuthConfig CRs to check for readiness? Conditions [`Available`](https://github.com/Kuadrant/authorino/blob/a8082ec35cfd112513fd0fb326c261fe153fb423/api/v1beta1/auth_config_types.go#L45) and [`Ready`](https://github.com/Kuadrant/authorino/blob/a8082ec35cfd112513fd0fb326c261fe153fb423/api/v1beta1/auth_config_types.go#L46) will tell you respectively when at least one host name listed in the AuthConfig has been indexed or all of them. The [`Summary`](https://github.com/Kuadrant/authorino/blob/a8082ec35cfd112513fd0fb326c261fe153fb423/api/v1beta1/auth_config_types.go#L665) field provides you with more details about which host names have been indexed (amongst other stuff).

(Not saying we couldn't use your suggestion to enhance the health check endpoint, BTW!)

**Comment by guicassolato** [comment]
@OperationalDev, it's a per-CR check and it won't give you the readiness state for the entire deployment, nor of any arbitrary pod for that matter. Rather, it gives you the state of a particular CR in the index, from the perspective of the leader replica, i.e. according to the one pod that won the dispute amongst all 3 replicas to become the leader Authorino replica and therefore it's responsible for updating the status sub-resource of the AuthConfigs. Unfortunately, we haven't yet implemented any synchronization between pods for the status update; that's why the value in the status sub-resource reflects only what the leader knows. On the other hand, it is relatively safe to assume that what the leader knows is either identical or no more than a couple milliseconds different (ahead or behind) what the other replicas know.

Checking the status sub-resource of a particular AuthConfig is straightforward. For example, given the AuthConfig from [this](https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/api-key-authentication.md#5-create-the-authconfig) example applied to the `default` namespace of the cluster, `.status.summary.ready` tells you if Authorino is ready to receive authz requests for the AuthConfig:

```sh
kubectl get authconfig/talker-api-protection -o jsonpath='{.status.summary.ready}'
```
Output:
```jsonc
true
```

In the example above, the AuthConfig lists only one host name, i.e. `talker-api-authorino.127.0.0.1.nip.io`. In this case, being _available_ (i.e. "at least one host name of the AuthConfig linked in the index") equals being _ready_ (i.e. "all host names  of the AuthConfig linked in the index"). In some other cases where you have more than one host name listed in the AuthConfig, due to [avoiding host name collisions](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#avoiding-host-name-collision), you can run into situations where an AuthConfig is _available_ but not _ready_. Because of that, you may want to check as well:

```sh
kubectl get authconfig/talker-api-protection -o jsonpath='{.status.conditions}'
```
Output:
```jsonc
[{"lastTransitionTime":"2022-10-17T09:37:36Z","reason":"HostsLinked","status":"True","type":"Available"},{"lastTransitionTime":"2022-10-17T09:37:36Z","reason":"Reconciled","status":"True","type":"Ready"}]
```

...and/or

```sh
kubectl get authconfig/talker-api-protection -o jsonpath='{.status.summary.hostsReady}'
```
Output:
```jsonc
["talker-api-authorino.127.0.0.1.nip.io"]
```

**Comment by OperationalDev** [comment]
@guicassolato It's not clear to me how I would use the status of the authconfigs to know which of the authorino pods are ready to serve requests?

**Comment by guicassolato** [comment]
@OperationalDev , sorry if I wasn't clear before. The status block in the authconfigs won't help you with which authorino pods are ready. Instead, it can only tell you whether the authconfig is ready in a particular authorino pod, specifically the leader one. My point from before is that the difference between being ready in the leader pod and being in any other pod should no more than a couple milliseconds away.

This is not ideal. I know! But hopefully it's enough to mitigate those 403s a little bit.

**Comment by OperationalDev** [comment]
Ok ok, sorry I misunderstood, thank you for clarifying.

**Comment by alexsnaps** [comment]
While not completely overlapping, it might be nice to consider this in the context of this issue: https://github.com/Kuadrant/kuadrant-controller/issues/211

**Comment by OperationalDev** [comment]
Just wanted to say thanks for the quick turn around time on this, working as expected.
