### ISSUE TITLE
Unable to list AuthConfigs due to conversion webhook error

### ISSUE THREAD

**Issue by pehala** [Kuadrant/authorino#429]
**Describe the bug**
`kubectl get authconfigs` returns
`Error from server: conversion webhook for authorino.kuadrant.io/v1beta1, Kind=AuthConfig failed: 0-length response with status code: 200 and content type: application/json` when in namespace that contains some AuthConfigs

**Comment by guicassolato** [comment]
Not sure we can avoid this 100%. I guess it's triggered because the webhook is stuck in a loop of errors, usually because it finished converting a resource but failed to generate a valid AuthConfig.

Other than working on those conversion errors, only thing I can think of right now is maybe having a validating webhook that takes conversion into account, but it doesn't seem right.

**Comment by pehala** [comment]
I would keep this open a bit longer to see if we can find other issues related to reconciliation and if not, we simply close it

**Comment by alexsnaps** [comment]
Would that be targeted to 0.17 and that would then be the version we want to ship with the [0.6.0 kuadrant release](https://github.com/Kuadrant/kuadrant-operator/issues/365)?

**Comment by guicassolato** [comment]
> Would that be targeted to 0.17 and that would then be the version we want to ship with the [0.6.0 kuadrant release](https://github.com/Kuadrant/kuadrant-operator/issues/365)?

This should be done. Can we close this now, @pehala?

**Comment by pehala** [comment]
Yup, we did not find additional issues with this. If we do we will reopen this.
